stages:
  - build
  - deploy

dotnet:
  stage: build
  image: microsoft/dotnet:latest
  script:
    - dotnet restore
	- dotnet build

push to github:
  stage: deploy
  image: watermelonpizza/git
  script:
    - git push -q --mirror https://$GITHUB_TOKEN@github.com/$GIT_REPO.git